ems/interface/web_interface/ems_builder/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^structures/', include('structures.urls')),
    url(r'^', include('structures.urls')),
]

ems/interface/web_interface/structures/urls.py
from django.conf.urls import url
from . import views


app_name = 'structures'

urlpatterns = [
    # /structures/
    url(r'^$', views.index, name='index'),
    url(r'^ems_message/$', views.ems_message, name='ems_message'),
    url(r'^check_ems_alerts/$', views.check_ems_alerts, name='check_ems_alerts'),
    url(r'^disable_alert/(?P<alert_id>[0-9]+)/$', views.disable_alert, name='disable_alert'),

    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<microgrid_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^create_microgrid/$', views.create_microgrid, name='create_microgrid'),
    url(r'^(?P<microgrid_id>[0-9]+)/delete_microgrid/$', views.delete_microgrid, name='delete_microgrid'),
    url(r'^(?P<microgrid_id>[0-9]+)/edit_microgrid/$', views.edit_microgrid, name='edit_microgrid'),
    url(r'^(?P<microgrid_id>[0-9]+)/export_microgrid/$', views.export_microgrid, name='export_microgrid'),
    url(r'^(?P<microgrid_id>[0-9]+)/clone_microgrid/$', views.clone_microgrid, name='clone_microgrid'),
    url(r'^(?P<microgrid_id>[0-9]+)/create_structure/(?P<structure_type>[\w\-]+)/(?P<structure_tag>[\w\-]+)/$',
        views.create_structure, name='create_structure'),
    url(r'^(?P<microgrid_id>[0-9]+)/delete_structure/(?P<structure_tag>[\w\-]+)/(?P<structure_id>[0-9]+)/$',
        views.delete_structure, name='delete_structure'),
    url(r'^(?P<microgrid_id>[0-9]+)/edit_structure/(?P<structure_tag>[\w\-]+)/(?P<structure_id>[0-9]+)/$',
        views.edit_structure, name='edit_structure'),
    url(r'^(?P<microgrid_id>[0-9]+)/create_task/(?P<appliance_tag>[\w\-]+)/(?P<profile_tag>[\w\-]+)/$',
        views.create_task, name='create_task'),
    url(r'^graphs/(?P<schedule_id>[0-9]+)/$', views.graphs, name='graphs'),
]

ems/interface/web_interface/structures/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.shortcuts import render, get_object_or_404, render_to_response

from .forms import *

from django.http import Http404

from ems_db.schedule.routines import *
from ems_db.sensor.routines import set_alert_status


def ems_message(request):
    if len(EMS_MESSAGES.messages) == 0 or EMS_MESSAGES is None:
        latest_message = 'Connecting to Energy Manager...'
    else:
        latest_message = EMS_MESSAGES.messages[-1]

    return render(request, 'structures/ems_message.html', {'latest_message': latest_message})


def check_ems_alerts(request):
    new_alerts_nr = EMS_ALERTS.check_new_alerts(get_active_alerts())

    return render(request, 'structures/check_ems_alerts.html', {'new_alerts_nr': new_alerts_nr})


def disable_alert(request, alert_id):
    set_alert_status(alert_id=alert_id, alert_status=False)
    EMS_ALERTS.delete_alert(alert_id)
    context = get_index_context(request.user)

    return render(request, 'structures/index.html', context)


def create_microgrid(request):
    if not request.user.is_authenticated():
        return render(request, 'structures/login.html')
    else:
        form = MicroGridForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            microgrid = form.save(commit=False)
            microgrid.user = request.user
            microgrid.save()
            set_default_structures(microgrid)
            context = {'microgrid': microgrid}
            update_detail_context(context)
            return render(request, 'structures/detail.html', context)
        context = {
            "form": form,
        }
        return render(request, 'structures/create_microgrid.html', context)


def set_default_structures(microgrid):
    for node_type in ['el', 'gas', 'heating', 'cooling', 'water']:
        default_node = Node()
        default_node.microgrid = microgrid
        default_node.type = node_type
        default_node.name = node_type.title()[0] + '-Node 1'
        default_node.save()

    # default_el_purchaser = Purchaser()
    # default_el_purchaser.microgrid = microgrid
    # default_el_purchaser.type = 'el'
    # default_el_purchaser.name = 'Default Electrical Grid'
    # default_el_purchaser.description = 'Default Electrical Grid'
    # default_el_purchaser.tag = 'purchaser'
    # default_el_purchaser.max = 3000.0
    # default_el_purchaser.profile = 'No profile.'
    # default_el_purchaser.save()
    # default_el_purchaser.nodes = microgrid.el_node_set()
    # default_el_purchaser.save()
    #
    # default_gas_purchaser = Purchaser()
    # default_gas_purchaser.microgrid = microgrid
    # default_gas_purchaser.type = 'gas'
    # default_gas_purchaser.name = 'Default Gas Grid'
    # default_gas_purchaser.description = 'Default Gas Grid'
    # default_gas_purchaser.tag = 'purchaser'
    # default_gas_purchaser.max = 3000.0
    # default_gas_purchaser.profile = 'No profile.'
    # default_gas_purchaser.save()
    # default_gas_purchaser.nodes = microgrid.gas_node_set()
    # default_gas_purchaser.save()

    return


def edit_microgrid(request, microgrid_id):
    microgrid = get_object_or_404(MicroGrid, pk=microgrid_id)
    form = MicroGridForm(request.POST or None, request.FILES or None, instance=microgrid)
    if form.is_valid():
        form.save()
        context = {'microgrid': microgrid}
        update_detail_context(context)
        return render(request, 'structures/detail.html', context)
    context = {
        'microgrid': microgrid,
        'form': form,
    }
    return render(request, 'structures/edit_structure.html', context)


def delete_microgrid(request, microgrid_id):
    microgrid = MicroGrid.objects.get(pk=microgrid_id)
    microgrid.delete()
    context = get_index_context(request.user)

    return render(request, 'structures/index.html', context)


def export_microgrid(request, microgrid_id):
    for microgrid in MicroGrid.objects.exclude(id=microgrid_id):
        microgrid.is_active = False
        microgrid.save()

    exported = MicroGrid.objects.get(id=microgrid_id)
    exported.is_active = True
    exported.save()

    with open(EMS_JSON_PATH, 'w') as outfile:
        json.dump(exported.to_json(), outfile)

    context = get_index_context(request.user)

    return render(request, 'structures/index.html', context)


def clone_microgrid(request, microgrid_id):
    cloned = MicroGrid.objects.get(id=microgrid_id)
    cloned.duplicate()

    context = get_index_context(request.user)

    return render(request, 'structures/index.html', context)


def create_structure(request, microgrid_id, structure_type, structure_tag):
    if not request.user.is_authenticated():
        return render(request, 'structures/login.html')
    else:
        microgrid = get_object_or_404(MicroGrid, pk=microgrid_id)
        form = get_structure_form(request, structure_tag=structure_tag)
        form.set_fields(microgrid=microgrid, type=structure_type, initialize=True)
        if form.is_valid():
            structure = form.save(commit=False)
            structure.microgrid = microgrid
            structure.tag = structure_tag
            structure.type = structure_type
            structure.save()
            form.save_m2m()
            context = {'microgrid': microgrid}
            update_detail_context(context)
            return render(request, 'structures/detail.html', context)
        context = {
            'microgrid': microgrid,
            'form': form,
        }

        if structure_tag in PROFILED_OBJECTS:
            profiles = get_profiles(structure_type=structure_type, structure_tag=structure_tag, microgrid=microgrid,
                                    output_data=True)

            context.update({'profiles': profiles})

        return render(request, 'structures/add_structure.html', context)


def edit_structure(request, microgrid_id, structure_tag, structure_id):
    if not request.user.is_authenticated():
        return render(request, 'structures/login.html')
    else:
        microgrid = get_object_or_404(MicroGrid, pk=microgrid_id)
        structure = get_structure(microgrid_id=microgrid_id, structure_tag=structure_tag, structure_id=structure_id)

        form = get_structure_form(request, structure_tag=structure.tag, structure=structure)

        form.set_fields(microgrid=microgrid, type=structure.type, initialize=False)

        if form.is_valid():
            form.save()
            context = {'microgrid': microgrid}
            update_detail_context(context)
            return render(request, 'structures/detail.html', context)
        context = {
            'microgrid': microgrid,
            'form': form,
        }

        profiles = get_profiles(structure_type=structure.type, structure_tag=structure_tag, microgrid=microgrid,
                                output_data=True)

    if len(profiles):
        context.update({'profiles': profiles})

    return render(request, 'structures/edit_structure.html', context)


def delete_structure(request, microgrid_id, structure_tag, structure_id):
    if not request.user.is_authenticated():
        return render(request, 'structures/login.html')
    else:
        microgrid = get_object_or_404(MicroGrid, pk=microgrid_id)
        structure = get_structure(microgrid_id=microgrid_id, structure_tag=structure_tag, structure_id=structure_id)
        structure.delete()
        context = {'microgrid': microgrid}
        update_detail_context(context)
        return render(request, 'structures/detail.html', context)


def create_task(request, microgrid_id, appliance_tag, profile_tag):
    if not request.user.is_authenticated():
        return render(request, 'structures/login.html')
    else:
        microgrid = get_object_or_404(MicroGrid, pk=microgrid_id)
        for appliance in APPLIANCES:
            if appliance['name'] == appliance_tag:
                for profile in appliance['profiles']:
                    if profile['name'] == profile_tag:
                        task_list = profile['tasks']
        form = MultiTaskForm(appliance_tag, task_list, request.POST or None, request.FILES or None)
        form.set_fields(microgrid)
        if form.is_valid():
            form.to_tasks()
            context = {'microgrid': microgrid}
            update_detail_context(context)
            return render(request, 'structures/detail.html', context)
        context = {
            'microgrid': microgrid,
            'form': form,
        }
        return render(request, 'structures/add_tasks.html', context)


def get_structure(microgrid_id, structure_tag, structure_id):
    microgrid = get_object_or_404(MicroGrid, pk=microgrid_id)
    if structure_tag == 'production':
        structure = microgrid.production_set.get(pk=structure_id)
    elif structure_tag == 'storage':
        structure = microgrid.storage_set.get(pk=structure_id)
    elif structure_tag == 'purchaser':
        structure = microgrid.purchaser_set.get(pk=structure_id)
    elif structure_tag == 'seller':
        structure = microgrid.seller_set.get(pk=structure_id)
    elif structure_tag == 'load':
        structure = microgrid.load_set.get(pk=structure_id)
    elif structure_tag == 'ep_load':
        structure = microgrid.epload_set.get(pk=structure_id)
    elif structure_tag == 'node':
        structure = microgrid.node_set.get(pk=structure_id)
    elif structure_tag == 'pipe':
        structure = microgrid.pipe_set.get(pk=structure_id)
    elif structure_tag == 'heater' or structure_tag == 'cooler':
        structure = microgrid.generator_set.get(pk=structure_id)
    elif structure_tag == 'cogenerator' or structure_tag == 'trigenerator':
        structure = microgrid.trigenerator_set.get(pk=structure_id)
    elif structure_tag == 'task':
        structure = microgrid.task_set.get(pk=structure_id)
    else:
        raise Exception('No valid tag')

    return structure

ems/interface/web_interface/structures/templates/structures/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'structures/style.css' %}"/>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'structures:index' %}">EMS Builder</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'structures:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'structures:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

ems/interface/web_interface/structures/templates/structures/check_ems_alerts.html
{% if new_alerts_nr = 0 %}
    <p>No new alerts.</p>
{% else %}
    {% if new_alerts_nr == 1 %}
        <strong>Found {{ new_alerts_nr }} new alert, <a href="{% url 'structures:index' %}">refresh</a> page to display it.</strong>
    {% else %}
        <strong>Found {{ new_alerts_nr }} new alerts, <a href="{% url 'structures:index' %}">refresh</a> page to display them.</strong>
    {% endif %}
{% endif %}

ems/interface/web_interface/structures/templates/structures/ems_message.html
<p>{{ latest_message }}</p>

ems/interface/web_interface/structures/templates/structures/index_grid.html
<div class="col-sm-5 col-lg-3">
    <div class="thumbnail">
        <div class="caption">
            {% if microgrid.is_active %}
                <h1 style="color: green;">{{ microgrid.name }}</h1>
            {% else %}
                <h1>{{ microgrid.name }}</h1>
            {% endif %}
            <h2>{{ microgrid.location }}</h2>
            <h4>Time Horizon: {{ microgrid.horizon }} min</h4>
            <h4>Time Resolution: {{ microgrid.resolution }} min</h4>

            <!-- MicroGrid Toolbar -->
            <div class="btn-toolbar" style="margin-bottom: 10px;">
                <a href="{% url 'structures:detail' microgrid.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                <button type="button" class="btn btn-basic btn-sm" data-toggle="modal" data-target="#cloneConfirm{{ microgrid.id }}">
                    Clone
                </button>
                <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#exportConfirm{{ microgrid.id }}">
                    Apply
                </button>
                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteConfirmGrid{{ microgrid.id }}">
                    <span class="glyphicon glyphicon-trash"></span>
                </button>
            </div>

            {% if microgrid.is_active %}
                <!-- Grid modification warning -->
                {% if microgrid.is_modified %}
                    <div class="alert alert-warning">
                        <strong>Warning!</strong> {{ microgrid.name }} has been modified, apply the new changes.
                    </div>
                {% endif %}

                <!-- New Alerts Warning -->
                <div class="btn-toolbar" style="margin-bottom: 10px;">
                    <button type="button" class="btn btn-info btn-sm" data-toggle="collapse" data-target="#alerts">Show Alerts</button>
                    <button type="button" class="btn btn-info btn-sm" data-toggle="collapse" data-target="#messages">Show Older Messages</button>
                </div>

                <!-- Alerts Table -->
                <div id="alerts" class="collapse">
                    {% if alerts|length == 0 %}
                        <strong>No alerts to display.</strong>
                    {% else %}
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th class="col-text">Alert Message</th>
                                    <th class="col-tools">
                                        <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for alert in alerts %}
                                    <tr>
                                        <td>
                                            {{ alert.msg }}
                                        </td>
                                        <td>
                                            <div class="btn-toolbar">
                                                <button type="button" class="btn btn-danger btn-xs" data-toggle="modal"
                                                        data-target="#dismissConfirmAlert{{ alert.id }}">
                                                    <span class="glyphicon glyphicon-trash"></span>
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                        {% for alert in alerts %}
                            <!-- Alert Dismiss Modal -->
                            <div class="modal fade" id="dismissConfirmAlert{{ alert.id }}" role="dialog" tabindex="-1"
                                 aria-labelledby="myModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h3>Warning</h3>
                                        </div>
                                        <div class="modal-body">
                                            Do you really want to dismiss {{ alert.msg|filter_1 }}?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">
                                                Cancel
                                            </button>
                                            <form action="{% url 'structures:disable_alert' alert.id %}" method="post" style="display: inline;">
                                                {% csrf_token %}
                                                <button type="submit" class="btn btn-danger">Dismiss</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                    {% endif %}
                </div>

                <!-- Alerts Table -->
                <div id="messages" class="collapse">
                    {% if messages|length == 0 %}
                        <strong>No old messages to display.</strong>
                    {% else %}
                        {% for message in messages %}
                            <p>{{ message }}</p>
                        {% endfor %}
                    {% endif %}
                </div>

                <!-- New Alerts Warning and update script -->
                <div class="alert alert-danger" id="check_ems_alerts">
                    {% include 'structures/check_ems_alerts.html' %}
                </div>
                <script>
                    var ALERT_URL = "{% url 'structures:check_ems_alerts' %}";
                    function refresh_alerts() {
                      $.ajax({
                      url: ALERT_URL,
                      success: function(data) {
                        $('#check_ems_alerts').html(data);
                      }
                     });
                    };

                    $(document).ready(function ($) {
                      refresh_alerts();
                      var int = setInterval("refresh_alerts()", 3000);
                    });
                </script>

                <!-- Latest message from EMS and update script -->
                <div class="alert alert-info" id="ems_message">
                    {% include 'structures/ems_message.html' %}
                </div>
                <script>
                    var MESSAGE_URL = "{% url 'structures:ems_message' %}";
                    function refresh_messages() {
                      $.ajax({
                      url: MESSAGE_URL,
                      success: function(data) {
                        $('#ems_message').html(data);
                      }
                     });
                    };

                    $(document).ready(function ($) {
                      refresh_messages();
                      var int = setInterval("refresh_messages()", 3000);
                    });
                </script>
            {% endif %}

            <!-- Clone Modal -->
            <div class="modal fade" id="cloneConfirm{{ microgrid.id }}" role="dialog" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h3>Warning</h3>
                        </div>
                        <div class="modal-body">
                            You are creating a copy of {{ microgrid.name }}: all structures will be cloned, but not tasks. Do you really want to proceed?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                            <form action="{% url 'structures:clone_microgrid' microgrid.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="microgrid_id" value="{{ microgrid.id }}" />
                                <button type="submit" class="btn btn-success">
                                    Yes, clone
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Export Modal -->
            <div class="modal fade" id="exportConfirm{{ microgrid.id }}" role="dialog" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h3>Warning</h3>
                        </div>
                        <div class="modal-body">
                            You are exporting a JSON representation of {{ microgrid.name }}. Do you really want to proceed?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                            <form action="{% url 'structures:export_microgrid' microgrid.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="microgrid_id" value="{{ microgrid.id }}" />
                                <button type="submit" class="btn btn-success">
                                    Yes, export
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Delete Modal -->
            <div class="modal fade" id="deleteConfirmGrid{{ microgrid.id }}" role="dialog" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h3>Warning</h3>
                        </div>
                        <div class="modal-body">
                            Do you really want to delete the MicroGrid?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                            <form action="{% url 'structures:delete_microgrid' microgrid.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>



        </div>
    </div>
</div>

ems/interface/web_interface/structures/templates/structures/left_info.html
<div class="panel panel-default">
    <div class="panel-body">
        <h1><a href="{% url 'structures:edit_microgrid' microgrid.id %}">{{ microgrid.name }}</a></h1>
        <h2>{{ microgrid.location }}</h2>
        <h4>Time Horizon: {{ microgrid.horizon }} min</h4>
        <h4>Time Resolution: {{ microgrid.resolution }} min</h4>
    </div>
</div>

ems/interface/web_interface/structures/templates/structures/login.html
{% extends 'structures/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'structures:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'structures:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

ems/interface/web_interface/structures/templates/structures/print_nodes.html
<table class="table table-striped">
    <thead>
        <tr>
            <th class="hidden-xs">ID</th>
            <th class="col-text">Name</th>
            <th class="col-tools">
                <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
            </th>
        </tr>
    </thead>
    {% for node in nodes %}
        <tr>
            <td>
                {{ node.tag }}-{{ node.id }}
            </td>
            <td>
                {{ node.name }}
            </td>
            <td>
                <div class="btn-toolbar">
                    <a class="btn btn-default btn-xs" href="{% url 'structures:edit_structure' node.microgrid.id node.tag node.id %}">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                    </a>
                    <button type="button" class="btn btn-danger btn-xs" data-toggle="modal"
                            data-target="#deleteConfirmNode{{ node.id }}">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </div>
            </td>
        </tr>

    {% endfor %}
</table>

{% for node in nodes %}
    <div class="modal fade" id="deleteConfirmNode{{ node.id }}" role="dialog" tabindex="-1"
                         aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h3>Warning</h3>
                                </div>
                                <div class="modal-body">
                                    Do you really want to delete {{ node.name|filter_1 }}?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">
                                        Cancel
                                    </button>
                                    <form action="{% url 'structures:delete_structure' node.microgrid.id node.tag node.id %}"
                                          method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger">Delete</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
{% endfor %}